print()
print("Hello user!")
print()
color = input('What is your favorite color? ').upper()
uncolor = input('What is your least favorite color? ').upper()
print()
print(f'Your favorite color is {color}, and your least favorite color is {uncolor}!!')