print()
plural_noun = input('What is a silly PLUARAL NOUN? ').title()
verb = input('What is a funny VERB? ').lower()
adjective = input('What is a weird ADJECTIVE? ').lower()
noun = input('What is a serious NOUN? ').capitalize()
name = input('What is a cool NAME? ').title()
location = input('What is an interesting location? ').title()
color = input('What is the prettiest color? ').lower()
size = input('What is a good size of cake? ').lower()
food = input('what is your favorite food? ').lower()
drink = input('What is the best beverage? ').lower()
shout = input('A good war cry. ').upper()
animal = input(f'What is the softest animal? ').title()
print()
# Note that I tried to do well by have at least ten varables in my code to show that I tried hard
# I personally do not know any madlibs, so I copied the first few lines of a book i like call "the way of kings" by Brandon Sanderson
print(f"{name} son son Valano, Truthless of {location}, wore {color} one the day he was going to kill a {noun}.")
print(f'The {color} clothing was a {animal} tradition, foreign to him. But he did as his masters required and did not ask for an explanation.')
print(f'He {verb} in a {size} stone room, baked by enormous firepits that that cast a {adjective} light upon the revelers')
print(f'causing as {plural_noun} of sweat to form on their skins they danced, and drank, and yelled {shout}, and sang, and {verb}.')
print(f'Some fell to the ground {color}-faced, the revelry too much for them, their stomachs proving to be inferior {drink}skins.')
print(f'They looked as if they were dead, at least until their friends carried them out of the feast hall to waiting beds.')
print(f'{name} did not sway to the drums, drink the sapphire {drink}, or stand to dance. He sat on a bench at the back, a still servant in white robes.')
print(f'Few at the treaty-signing celebration noticed him. He was just a servant, and Shin were easy to ignore.')
print(f'Most out here in {location} thought {name} kind were docile and harmless. They were generally right.')
print(f'The drummers began a new rhythm. The beats shook {name} like a quartet of thumping hearts, pumping waves of invisible blood through the room.')
print(f'{name}s masters—who were dismissed as savages by those in more civilized kingdoms—sat at their own tables.')
print()
print(f'They were {animal} with skin of black marbled with red. They also said {shout} a lot which was weird.')
print(f'{animal}, they were named—cousins to the more docile servant peoples known as parsh{animal} in most of the world. An oddity.')
print(f'They did not call themselves {animal}; this was the Alethi name for them.')
print(f'It meant, roughly, “parsh{animal} who can think.” Neither side seemed to see that as an insult.')
print(f'The {animal} had brought the musicians. At first, the Alethi lighteyes had been hesitant. To them, drums were base instruments of the common, darkeyed people.')
print(f'But {drink} was the great assassin of both tradition and propriety, and now the Alethi elite danced with abandon.')
print(f'{name} stood and began to pick his way through the {size} room. The revelry had lasted long; even the king had retired hours ago. But many still celebrated.')
print(f'As he walked, {name} was forced to step around Dalinar Kholin—the {noun} own brother—who slumped drunken at a small table.')
print(f'The aging but powerfully built man kept waving away those who tried to encourage him to bed. Where was Jasnah, the {noun} daughter?')
print(f'Elhokar, the {noun} son and heir, sat at the high table, ruling the feast in his fathers absence.')
print(f'He was in conversation with two {animal}, a dark-skinned Azish man who had an odd patch of pale skin on his cheek and a thinner, Alethi-looking man who kept glancing over his shoulder.')
print()
# now it should again be noted that no matter the case put in it auto matically fixes its self to the right casing
# Also I added about 20 lines of story. Hope you had fun reading whoever may read this.