first_name = input("What is your first name? ")
last_name = input("what is your last name? ")
email_address = input("what is your email address? ")
phone_number = input("What is your your phone number? ")
job_title = input('What is your job title? ')
ID_number = input("What is your ID number? ")
print()
print('--------------------------------------------------------')
print(f'{last_name}, {first_name}')
print(f'{job_title}')
print(f'ID: {ID_number}')
print()
print(f'{email_address}')
print(f'{phone_number}')
print('--------------------------------------------------------')