print()
print("Please enter the following information")
print()
noun_1 = input("A noun: ").lower()
animal_1 = input('An animal: ').lower()
animal_2 = input("A different animal: ").lower()
place_1 = input("A place: ").capitalize()
time_1 = input("A year: ").lower()
person_1 = input("A famous person: ").title()
verb_1 = input("A verb: ").lower()
verb_2 = input("Another verd: ").lower()
shout_1 = input("An exclaimation: ").upper()
adjective_1 = input("An adjective: ").lower()
adjective_2 = input("A different adjective: ").lower()
adjective_3 = input("Another adjective: ").lower()
adjective_4 = input("One last adjective: ").lower()
print()
print(f"Important knowledge you need to know about {animal_1}.")
print(f"Once upon a {noun_1}, there were {animal_1}'s.")
print(f"They lived in a {place_1}, where they ate {adjective_1} stuff.")
print(f"People first discovered they in {time_1} when {person_1} first taught one how to {verb_1}.")
print(f"When people first realized this they said {shout_1} and started to {verb_2}.")
print(f"Then, people said it was {adjective_2}.")
print(f"This is why {animal_1}'s, are very {adjective_3} and {animal_2}'s won't go near them.")
print(f"But the turth is these animals are very {adjective_4}.")
print()