
print("Please enter the following information")
print()
first_name = input("First name: ").capitalize()
last_name = input("Last name: ").upper()
middle_initial = input("Middle intial: ").upper()
email_address = input("Email address: ").lower()
phone_number = input("Phone number: ")
job_title = input("Job Title: ").title()
id_number = input("ID Number: ")
print()
print("The ID card is:")
print("-----------------------------------------------------")
print(f"{last_name}, {first_name}, {middle_initial}")
print(job_title)
print("ID: ", id_number)
print()
print(email_address)
print(phone_number)
print("-----------------------------------------------------")