import math
print()
mass = float (input ("What is the mass of the object in Kilos?"))
print ("9.8 for Earth and 24 for Jupiter.")
print()
acceleration = float (input ("What is the acceleration due to gravit?"))
print()
time =  float (input ("What is the time spent in the air in seconds?"))
print()
light = 0.003
print ("1.3 kg/m^3 for air, 1000 kg/m^3 for water")
density = float (input ("What is the density of the space?"))
print()
print("in square meters")
cross = float (input ("What is the cross sectional area of projectile?"))
print()
print ("0.5 for sphere, 1.1 for cylinder falling on its side...")
drag = float (input ("What is the drag constant?"))
print()
velocity = math.sqrt(mass * acceleration / light) * (1 - math.exp((-math.sqrt(mass * acceleration * light) / mass) * time))
print (f"The velocity after {time} seconds is: {velocity} m/s")
